<?php

   $example = "TAGTTATTAATAGTAATCAATTACGGGGTCATTAGTTCATAGCCCATATATGGAGTTCCGCGTTACATAACTTACGGTAAATGGCCCGG";
   if (isset($_POST["reset"])) { 
     $_POST["data"] = NULL; 
     /*
     $command = "cat input.txt";
     exec($command, $out);
     $p_data = NULL;
     for ($i = 0; $i < count($out); $i++) { $p_data .= $out[$i]."\n"; }
      */
     $p_data = $example;
   } else {
      if (isset($_POST["data"])) { $p_data = $_POST["data"]; }
   }
   if ($p_data == NULL) { $p_data = $example; }
   //echo "<br><form action='https://www.pnabio.com/support/vincent/' method='post' ";
   echo "<form action='Donor_Designer_Py.php' method='post' ";
   echo " onsubmit='submitButton.disabled=true; return true;' >";
   echo "<div style='padding: 10px 0px;'><font style='font-family:Verdana; font-size:14px;' color='#015182'><b>Enter Target Sequence </font></b> <font style='font-family:Verdana; font-size:12px;' color='#333333'>(in frame, no space, maximum500 bp):</font><br></div>";
//<input style="width:100%" type="text" name="InsertString" value="TAGTTATTAATAGTAATCAATTACGGGGTCATTAGTTCATAGCCCATATATGGAGTTCCGCGTTACATAACTTACGGTAAATGGCCCGG" size="500"><br><br>

   echo "<textarea rows='3' cols='80' name='data'>$p_data</textarea><br><br>";
   echo "<font style='font-family:Verdana; font-size:12px;' color='#333333'>";
   echo "The list of restriction enzymes can be found <a href='RE_list.pdf' target='_blank'>here</a>.  <br><br>";

   echo "<input type='submit' name='submitButton' value='Find Mutations' />&nbsp;";
   echo "<input type='submit' name='reset' value='Reset' />";
   echo "</form></center>";
   echo "<br>";

   if (!isset($_POST["data"])) {
      echo "<br><br>";

   } else {
      $tmpfname = tempnam("/var/tmp", "findMut");
      $handle = fopen($tmpfname, "w");
      fwrite($handle, $p_data);
      fclose($handle);
      $command = "python findMut.py ".$tmpfname;
      unset($out);
      exec($command, $out);
      echo "<br><br>";
/*
      echo "<table id='avc' border='0'>";
                  echo "<tr>";
                  for ($j = 0; $j < count($a_out); $j++) {
                     if (is_numeric($a_out[$j])) { $bgcolor="white"; } else { $bgcolor="CCCCCC"; }
                     echo "<td bgcolor=$bgcolor><center>".$a_out[$j]."</center></td>";
                  }
                  echo "</tr>";

 */

      for ($i = 0; $i < count($out); $i++) { echo $out[$i]."<br>\n"; }
      echo "<br>";
      unlink($tmpfname); 
    }

    echo "The Donor Designer tool offers a customized DNA sequence that incorporates mutations, allowing for the creation of restriction sites while maintaining the amino acid sequences. The purpose of this tool is to aid in the design of a knock-in donor by suggesting suitable restriction sites to streamline the KI screening process. Donor Designer can recommend restriction sites that can be generated by introducing 1, 2, or 3 base mutations.";

    echo "<br><br><br>";
    echo "<font style='font-family:Verdana; font-size:12px;' color='#333333'>";
    echo "Any questions or comments, please call us at 805) 504-2220 or send an email to <a href='mailto:info@pnabio.com'><font='verdana'; style=' color:blue; text-decoration:underline;'><i> info@pnabio.com</i></font></a>. </font><br>";
    echo "<br>";

?>
